#!/bin/zsh
#
# export-env.sh — Build a Wonder Cabinet .env for a remote environment.
#
# Secrets are pulled from either:
#   - macOS login keychain (developer.workspace.* entries), OR
#   - interactive prompts (--manual mode, for iCloud Keychain users)
#
# Usage:
#   ./scripts/export-env.sh                # auto from login keychain → .env
#   ./scripts/export-env.sh --manual       # prompt for each secret → .env
#   ./scripts/export-env.sh --output path  # write to a specific file
#   ./scripts/export-env.sh --store        # save secrets INTO login keychain
#   ./scripts/export-env.sh --print        # print to stdout (no file)
#
set -euo pipefail

# ── Secrets we need ──
SECRET_NAMES=(
  GHOST_ADMIN_API_KEY
  PRX_CLIENT_ID
  PRX_CLIENT_SECRET
  AIRTABLE_API_KEY
  YOUTUBE_CLIENT_ID
  YOUTUBE_CLIENT_SECRET
  TALLY_API_KEY
)

# ── Optional secrets (no warning if missing) ──
OPTIONAL_SECRETS=(YOUTUBE_CLIENT_ID YOUTUBE_CLIENT_SECRET TALLY_API_KEY)

# ── Login keychain service names (developer.workspace.* convention) ──
typeset -A KEYCHAIN_KEYS=(
  GHOST_ADMIN_API_KEY   "developer.workspace.GHOST_ADMIN_API_KEY"
  PRX_CLIENT_ID         "developer.workspace.PRX_CLIENT_ID"
  PRX_CLIENT_SECRET     "developer.workspace.PRX_CLIENT_SECRET"
  AIRTABLE_API_KEY      "developer.workspace.AIRTABLE_API_KEY"
  YOUTUBE_CLIENT_ID     "developer.workspace.YOUTUBE_CLIENT_ID"
  YOUTUBE_CLIENT_SECRET "developer.workspace.YOUTUBE_CLIENT_SECRET"
  TALLY_API_KEY         "developer.workspace.TALLY_API_KEY"
)

OUTPUT_FILE=".env"
MODE="keychain"

# ── Parse arguments ──
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output|-o)  OUTPUT_FILE="$2"; shift 2 ;;
    --manual|-m)  MODE="manual"; shift ;;
    --store|-s)   MODE="store"; shift ;;
    --print|-p)   MODE="print"; shift ;;
    --help|-h)
      echo "Usage: $0 [--manual] [--output FILE] [--store] [--print]"
      echo ""
      echo "  --manual, -m        Prompt for each secret interactively"
      echo "                      (use if secrets are in iCloud Keychain)"
      echo "  --output, -o FILE   Write .env to FILE (default: .env)"
      echo "  --store, -s         Save secrets into macOS login keychain"
      echo "  --print, -p         Print .env to stdout instead of file"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Helpers ──
keychain_get() {
  security find-generic-password -s "$1" -w 2>/dev/null || true
}

keychain_set() {
  security delete-generic-password -s "$1" 2>/dev/null || true
  security add-generic-password -s "$1" -a "$USER" -w "$2"
}

is_optional() {
  local name="$1"
  for opt in "${OPTIONAL_SECRETS[@]}"; do
    [[ "$opt" == "$name" ]] && return 0
  done
  return 1
}

# ── Store mode: prompt and save to login keychain ──
if [[ "$MODE" == "store" ]]; then
  echo "Storing secrets in macOS login keychain..."
  echo "(Press Enter to skip any value you don't want to update)"
  echo ""

  for name in "${SECRET_NAMES[@]}"; do
    local service="${KEYCHAIN_KEYS[$name]}"
    local existing=$(keychain_get "$service")

    if [[ -n "$existing" ]]; then
      local masked="${existing[1,6]}...${existing[-4,-1]}"
      echo "$name (current: $masked)"
    else
      echo "$name (not set)"
    fi

    read -rs "value?  New value: "
    echo ""

    if [[ -n "$value" ]]; then
      keychain_set "$service" "$value"
      echo "  -> Saved as $service"
    else
      echo "  -> Skipped"
    fi
  done

  echo ""
  echo "Done. Run '$0' to export a .env file."
  exit 0
fi

# ── Collect secrets ──
typeset -A SECRET_VALUES
missing=()

if [[ "$MODE" == "manual" ]]; then
  echo "Enter secrets from iCloud Keychain / Passwords app."
  echo "(Press Enter to skip optional values)"
  echo ""

  for name in "${SECRET_NAMES[@]}"; do
    local optional_label=""
    is_optional "$name" && optional_label=" [optional]"

    read -rs "value?${name}${optional_label}: "
    echo ""

    if [[ -n "$value" ]]; then
      SECRET_VALUES[$name]="$value"
    elif ! is_optional "$name"; then
      missing+=("$name")
    fi
  done
  echo ""

else
  # Pull from login keychain
  for name in "${SECRET_NAMES[@]}"; do
    local service="${KEYCHAIN_KEYS[$name]}"
    local value=$(keychain_get "$service")
    if [[ -n "$value" ]]; then
      SECRET_VALUES[$name]="$value"
    elif ! is_optional "$name"; then
      missing+=("$name")
    fi
  done
fi

# ── Build .env content ──
build_env() {
  cat <<'HEADER'
# ══════════════════════════════════════════════════════════════
# Wonder Cabinet Productions — Remote Environment
# Generated by scripts/export-env.sh
# ══════════════════════════════════════════════════════════════

HEADER

  echo "# ── Ghost CMS ──────────────────────────────────────────────"
  echo "GHOST_URL=https://wonder-cabinet.ghost.io"
  echo "GHOST_SITE_URL=https://wondercabinetproductions.com"
  echo "GHOST_ADMIN_API_KEY=${SECRET_VALUES[GHOST_ADMIN_API_KEY]:-<MISSING>}"
  echo ""

  echo "# ── PRX / Dovetail ─────────────────────────────────────────"
  echo "PRX_FEED_URL=https://publicfeeds.net/f/120/wondercabinet"
  echo "PRX_PODCAST_ID=120"
  echo "PRX_PODCAST_IDS=120,3329"
  echo "PRX_CLIENT_ID=${SECRET_VALUES[PRX_CLIENT_ID]:-<MISSING>}"
  echo "PRX_CLIENT_SECRET=${SECRET_VALUES[PRX_CLIENT_SECRET]:-<MISSING>}"
  echo "PRX_USE_API=true"
  echo ""

  echo "# ── Airtable ───────────────────────────────────────────────"
  echo "AIRTABLE_API_KEY=${SECRET_VALUES[AIRTABLE_API_KEY]:-<MISSING>}"
  echo ""

  echo "# ── Audiogram / YouTube (optional) ─────────────────────────"
  echo "YOUTUBE_CLIENT_ID=${SECRET_VALUES[YOUTUBE_CLIENT_ID]:-}"
  echo "YOUTUBE_CLIENT_SECRET=${SECRET_VALUES[YOUTUBE_CLIENT_SECRET]:-}"
  echo "YOUTUBE_REDIRECT_URI=http://localhost:3000/oauth2callback"
  echo ""

  echo "# ── Tally.so (contact form) ────────────────────────────────"
  echo "TALLY_API_KEY=${SECRET_VALUES[TALLY_API_KEY]:-}"
  echo ""

  echo "# ── Whisper Transcription ──────────────────────────────────"
  echo "WHISPER_MODEL=turbo"
  echo "WHISPER_BACKEND=auto"
  echo ""

  echo "# ── Pipeline Defaults ──────────────────────────────────────"
  echo "PUBLISH_STATUS=draft"
  echo "DRY_RUN=false"
}

# ── Output ──
if [[ "$MODE" == "print" ]]; then
  build_env
else
  build_env > "$OUTPUT_FILE"
  echo "Wrote $OUTPUT_FILE"

  if [[ ${#missing[@]} -gt 0 ]]; then
    echo ""
    echo "⚠  Missing required secrets:"
    for m in "${missing[@]}"; do
      echo "   - $m"
    done
    echo ""
    echo "Re-run with --manual to enter them interactively."
  fi

  echo ""
  echo "Copy to remote:  scp $OUTPUT_FILE user@host:/path/to/project/.env"
fi
